import type { RestauranteDemo } from "../tipos";

export const CAFE: RestauranteDemo[] = [
  {
    slug: "barrio-tostado",
    nombre: "Barrio Tostado",
    descripcion:
      "Espresso bar de barrio con panadería propia y mesas que dan a la acera. Llegá temprano por el cold brew de la casa, que vuela antes del mediodía.",
    categoria: "Café",
    cocina: "Espresso bar y panadería",
    zona: "San José centro",
    direccion: "Plaza del Reloj, local 3",
    telefono: "+506 2555-0141",
    precioNivel: 1,
    precioPromedio: 4800,
    menu: [
      {
        nombre: "Capuchino de la casa",
        precio: 2900,
        foto: "/food-demo/m/cafe-1.jpg",
      },
      {
        nombre: "Cold brew de tueste propio",
        descripcion: "Reposado toda la noche en frío; el que vuela antes del mediodía.",
        precio: 3400,
        foto: "/food-demo/m/cafe-6.jpg",
      },
      {
        nombre: "Croissant de mantequilla recién horneado",
        precio: 3100,
        foto: "/food-demo/m/cafe-2.jpg",
      },
      {
        nombre: "Tostada de aguacate con huevo de finca",
        descripcion: "Pan de masa madre de la panadería, aguacate machacado y hojuelas de chile.",
        precio: 6200,
        foto: "/food-demo/m/cafe-3.jpg",
      },
      {
        nombre: "Benedictinos del barrio",
        precio: 7900,
        foto: "/food-demo/m/cafe-8.jpg",
      },
      {
        nombre: "Rol de canela glaseado",
        precio: 3700,
        foto: "/food-demo/m/cafe-7.jpg",
      },
    ],
    rating: 4.6,
    resenas: 214,
    fotoPrincipal: "/food-demo/r/barrio-tostado-1.jpg",
    galeria: ["/food-demo/r/barrio-tostado-2.jpg", "/food-demo/r/barrio-tostado-3.jpg"],
    horario: "Lun–Sáb · 7:00 – 19:00",
    promociones: [
      { hora: "07:30", descuento: 20 },
      { hora: "10:00", descuento: 30 },
      { hora: "11:30", descuento: 10 },
      { hora: "13:00", descuento: 15 },
      { hora: "15:00", descuento: 25 },
      { hora: "17:00", descuento: 20 },
    ],
  },
  {
    slug: "molienda-once",
    nombre: "Molienda Once",
    descripcion:
      "A dos cuadras del bullicio universitario, acá se tuesta en sitio y se sirve hasta la noche. Ideal para estudiar, conversar o simplemente quedarse una taza más.",
    categoria: "Café",
    cocina: "Café de especialidad y repostería",
    zona: "San Pedro",
    direccion: "Centro Comercial Vitral, local 21",
    telefono: "+506 2555-0152",
    precioNivel: 1,
    precioPromedio: 4200,
    menu: [
      {
        nombre: "Queque de zanahoria con lustre de queso crema",
        precio: 3300,
        foto: "/food-demo/m/cafe-5.jpg",
      },
      {
        nombre: "Latte doble de la molienda",
        descripcion: "Grano tostado en sitio esa misma semana, con arte en la leche.",
        precio: 2700,
        foto: "/food-demo/m/cafe-1.jpg",
      },
      {
        nombre: "Rol de canela tibio",
        precio: 3400,
        foto: "/food-demo/m/cafe-7.jpg",
      },
      {
        nombre: "Tostada de aguacate con queso de cabra",
        precio: 5800,
        foto: "/food-demo/m/cafe-3.jpg",
      },
      {
        nombre: "Pancakes trasnochados con frutas",
        descripcion: "Se sirven hasta el cierre — el combustible oficial de época de exámenes.",
        precio: 6900,
        foto: "/food-demo/m/cafe-4.jpg",
      },
      {
        nombre: "Café helado en vaso alto",
        precio: 3100,
        foto: "/food-demo/m/cafe-6.jpg",
      },
    ],
    rating: 4.4,
    resenas: 58,
    fotoPrincipal: "/food-demo/r/molienda-once-1.jpg",
    galeria: ["/food-demo/r/molienda-once-2.jpg", "/food-demo/r/molienda-once-3.jpg"],
    horario: "Lun–Dom · 8:00 – 21:00",
    promociones: [
      { hora: "11:00", descuento: 10 },
      { hora: "14:30", descuento: 20 },
      { hora: "16:00", descuento: 25 },
      { hora: "18:30", descuento: 40 },
      { hora: "20:00", descuento: 45 },
      { hora: "20:30", descuento: 30 },
    ],
  },
  {
    slug: "niebla-y-grano",
    nombre: "Niebla y Grano",
    descripcion:
      "Granos de altura de la zona, servidos en una barra de métodos con catas guiadas los fines de semana. ¿El resultado? Una taza que sabe a la montaña de donde vino.",
    categoria: "Café",
    cocina: "Café de altura y métodos",
    zona: "Cartago",
    direccion: "Centro Comercial Brumas, local 7",
    telefono: "+506 2555-0163",
    precioNivel: 2,
    precioPromedio: 8200,
    menu: [
      {
        nombre: "Benedictinos de la niebla",
        descripcion: "Huevos pochados con holandesa de chile dulce ahumado y tocineta del valle.",
        precio: 11800,
        foto: "/food-demo/m/cafe-8.jpg",
      },
      {
        nombre: "Pancakes de altura con frutas de temporada",
        precio: 9800,
        foto: "/food-demo/m/cafe-4.jpg",
      },
      {
        nombre: "Tostada de aguacate con huevo pochado",
        precio: 9600,
        foto: "/food-demo/m/cafe-3.jpg",
      },
      {
        nombre: "Queque de zanahoria con nuez",
        precio: 6900,
        foto: "/food-demo/m/cafe-5.jpg",
      },
      {
        nombre: "Capuchino de origen único",
        descripcion: "Grano de un solo microlote de la zona; preguntá cuál está en barra.",
        precio: 4300,
        foto: "/food-demo/m/cafe-1.jpg",
      },
      {
        nombre: "Cold brew reposado 12 horas",
        precio: 4800,
        foto: "/food-demo/m/cafe-6.jpg",
      },
    ],
    rating: 4.8,
    resenas: 341,
    fotoPrincipal: "/food-demo/r/niebla-y-grano-1.jpg",
    galeria: ["/food-demo/r/niebla-y-grano-2.jpg", "/food-demo/r/niebla-y-grano-3.jpg"],
    horario: "Mié–Dom · 9:00 – 18:00",
    promociones: [
      { hora: "09:30", descuento: 15 },
      { hora: "11:30", descuento: 40 },
      { hora: "12:30", descuento: 50 },
      { hora: "14:00", descuento: 35 },
      { hora: "16:30", descuento: 20 },
    ],
  },
  {
    slug: "patio-cedro",
    nombre: "Patio Cedro",
    descripcion:
      "Un patio arbolado donde el brunch no anda de prisa: pancakes, pan artesanal y café chorreado al estilo de antes. Vení con tiempo y pedí la mesa bajo el cedro.",
    categoria: "Café",
    cocina: "Brunch y café chorreado",
    zona: "Alajuela",
    direccion: "Paseo del Mango, local 15",
    telefono: "+506 2555-0174",
    precioNivel: 1,
    precioPromedio: 6300,
    menu: [
      {
        nombre: "Pancakes bajo el cedro con miel de tapa",
        descripcion: "La torre de la casa, con frutas frescas y mantequilla derretida.",
        precio: 7800,
        foto: "/food-demo/m/cafe-4.jpg",
      },
      {
        nombre: "Benedictinos criollos con tortilla palmeada",
        precio: 9400,
        foto: "/food-demo/m/cafe-8.jpg",
      },
      {
        nombre: "Tostada de aguacate con pico de gallo",
        precio: 7200,
        foto: "/food-demo/m/cafe-3.jpg",
      },
      {
        nombre: "Croissant artesanal del horno de leña",
        precio: 3400,
        foto: "/food-demo/m/cafe-2.jpg",
      },
      {
        nombre: "Rol de canela del patio",
        precio: 4200,
        foto: "/food-demo/m/cafe-7.jpg",
      },
      {
        nombre: "Capuchino con leche de la zona",
        descripcion: "Café chorreado al estilo de antes, coronado con leche cremada.",
        precio: 3200,
        foto: "/food-demo/m/cafe-1.jpg",
      },
      {
        nombre: "Queque de zanahoria casero",
        precio: 4600,
        foto: "/food-demo/m/cafe-5.jpg",
      },
    ],
    rating: 4.7,
    resenas: 96,
    fotoPrincipal: "/food-demo/r/patio-cedro-1.jpg",
    galeria: ["/food-demo/r/patio-cedro-2.jpg", "/food-demo/r/patio-cedro-3.jpg"],
    horario: "Mar–Dom · 8:30 – 17:30",
    promociones: [
      { hora: "08:30", descuento: 10 },
      { hora: "10:30", descuento: 15 },
      { hora: "12:00", descuento: 20 },
      { hora: "14:30", descuento: 30 },
      { hora: "15:30", descuento: 35 },
      { hora: "16:30", descuento: 25 },
      { hora: "17:00", descuento: 15 },
    ],
  },
];
