import type { RestauranteDemo } from "../tipos";

export const CARNES: RestauranteDemo[] = [
  {
    slug: "cumbre-brasa",
    nombre: "Cumbre & Brasa",
    descripcion:
      "Cortes madurados en seco y una cava que impresiona desde la entrada. Vení por el tomahawk, quedate por la sobremesa con vista al valle.",
    categoria: "Carnes",
    cocina: "Steakhouse de autor",
    zona: "Escazú",
    direccion: "Centro Comercial Alto Verde, local 21",
    telefono: "+506 2555-0141",
    precioNivel: 4,
    precioPromedio: 28500,
    menu: [
      {
        nombre: "Tomahawk madurado 28 días",
        descripcion: "Corte de 1 kg para compartir, sellado sobre brasa de encino.",
        precio: 42000,
        foto: "/food-demo/m/carnes-1.jpg",
      },
      {
        nombre: "Ribeye de la cava",
        precio: 29500,
        foto: "/food-demo/m/carnes-4.jpg",
      },
      {
        nombre: "Lomito en salsa de hongos silvestres",
        descripcion: "Medallón de lomito con hongos salteados y reducción de vino tinto.",
        precio: 26500,
        foto: "/food-demo/m/carnes-5.jpg",
      },
      {
        nombre: "Costillar de res ahumado",
        precio: 31500,
        foto: "/food-demo/m/carnes-2.jpg",
      },
      {
        nombre: "New York con vegetales rostizados",
        precio: 24500,
        foto: "/food-demo/m/carnes-3.jpg",
      },
      {
        nombre: "Chorizo artesanal de la casa",
        precio: 18500,
        foto: "/food-demo/m/carnes-8.jpg",
      },
    ],
    rating: 4.8,
    resenas: 214,
    fotoPrincipal: "/food-demo/r/cumbre-brasa-1.jpg",
    galeria: ["/food-demo/r/cumbre-brasa-2.jpg", "/food-demo/r/cumbre-brasa-3.jpg"],
    horario: "Mar–Dom · 12:00 – 23:00",
    promociones: [
      { hora: "12:30", descuento: 15 },
      { hora: "17:00", descuento: 30 },
      { hora: "17:30", descuento: 40 },
      { hora: "18:00", descuento: 35 },
      { hora: "19:30", descuento: 20 },
      { hora: "21:00", descuento: 10 },
    ],
  },
  {
    slug: "fuego-manso",
    nombre: "Fuego Manso",
    descripcion:
      "La parrilla trabaja desde media mañana para que el almuerzo llegue en su punto. Cortes al carbón, tortillas palmeadas y cero carreras.",
    categoria: "Carnes",
    cocina: "Parrilla al carbón",
    zona: "Santa Ana",
    direccion: "Plaza Lucero, local 5",
    telefono: "+506 2555-0152",
    precioNivel: 3,
    precioPromedio: 18500,
    menu: [
      {
        nombre: "Costillas de cerdo al carbón",
        descripcion: "Tres horas de humo y un final sobre brasa viva, con tortillas palmeadas.",
        precio: 19500,
        foto: "/food-demo/m/carnes-6.jpg",
      },
      {
        nombre: "Churrasco con chimichurri de la casa",
        precio: 17500,
        foto: "/food-demo/m/carnes-3.jpg",
      },
      {
        nombre: "Pinchos mixtos del asador",
        precio: 16500,
        foto: "/food-demo/m/carnes-7.jpg",
      },
      {
        nombre: "Chorizo criollo con tortilla",
        precio: 12500,
        foto: "/food-demo/m/carnes-8.jpg",
      },
      {
        nombre: "Costilla alta ahumada",
        descripcion: "Porción generosa con papas gajo y ensalada fresca.",
        precio: 22500,
        foto: "/food-demo/m/carnes-2.jpg",
      },
      {
        nombre: "Bife ancho reposado",
        precio: 22000,
        foto: "/food-demo/m/carnes-4.jpg",
      },
    ],
    rating: 4.6,
    resenas: 87,
    fotoPrincipal: "/food-demo/r/fuego-manso-1.jpg",
    galeria: ["/food-demo/r/fuego-manso-2.jpg", "/food-demo/r/fuego-manso-3.jpg"],
    horario: "Lun–Sáb · 11:30 – 22:00",
    promociones: [
      { hora: "11:30", descuento: 35 },
      { hora: "12:00", descuento: 45 },
      { hora: "12:30", descuento: 40 },
      { hora: "13:30", descuento: 25 },
      { hora: "14:00", descuento: 15 },
      { hora: "18:30", descuento: 10 },
    ],
  },
  {
    slug: "ceniza-sal",
    nombre: "Ceniza & Sal",
    descripcion:
      "Acá todo pasa por la brasa, del lomito a los vegetales. Ideal si buscás una cena larga, a media luz y sin apuro.",
    categoria: "Carnes",
    cocina: "Cocina de fuego",
    zona: "Belén",
    direccion: "Plaza del Molino, local 14",
    telefono: "+506 2555-0163",
    precioNivel: 4,
    precioPromedio: 31000,
    menu: [
      {
        nombre: "Lomito a las brasas en salsa de hongos",
        descripcion: "Hongos silvestres, tomillo y un fondo oscuro que se termina en la mesa.",
        precio: 32500,
        foto: "/food-demo/m/carnes-5.jpg",
      },
      {
        nombre: "Tomahawk a dos fuegos",
        descripcion: "El corte insignia: una hora de rescoldo lento y sellado final al fuego vivo.",
        precio: 45000,
        foto: "/food-demo/m/carnes-1.jpg",
      },
      {
        nombre: "Costillar lacado en su jugo",
        precio: 33500,
        foto: "/food-demo/m/carnes-2.jpg",
      },
      {
        nombre: "Ribeye reposado al rescoldo",
        precio: 34500,
        foto: "/food-demo/m/carnes-4.jpg",
      },
      {
        nombre: "Brochetas de la brasa",
        precio: 25500,
        foto: "/food-demo/m/carnes-7.jpg",
      },
      {
        nombre: "Asado de tira con vegetales tatemados",
        precio: 29500,
        foto: "/food-demo/m/carnes-3.jpg",
      },
      {
        nombre: "Chorizo de finca con miel de chile",
        precio: 16500,
        foto: "/food-demo/m/carnes-8.jpg",
      },
    ],
    rating: 4.9,
    resenas: 391,
    fotoPrincipal: "/food-demo/r/ceniza-sal-1.jpg",
    galeria: ["/food-demo/r/ceniza-sal-2.jpg", "/food-demo/r/ceniza-sal-3.jpg"],
    horario: "Mié–Dom · 17:00 – 23:30",
    promociones: [
      { hora: "17:00", descuento: 10 },
      { hora: "18:30", descuento: 15 },
      { hora: "20:00", descuento: 35 },
      { hora: "20:30", descuento: 50 },
      { hora: "21:00", descuento: 45 },
      { hora: "21:30", descuento: 30 },
    ],
  },
  {
    slug: "brasa-del-llano",
    nombre: "Brasa del Llano",
    descripcion:
      "Un asador de patio con sabor a domingo alajuelense: costillas ahumadas, chimichurri de la casa y porciones que dan abasto.",
    categoria: "Carnes",
    cocina: "Asador criollo",
    zona: "Alajuela",
    direccion: "Centro Comercial Valle Claro, local 9",
    telefono: "+506 2555-0174",
    precioNivel: 3,
    precioPromedio: 16500,
    menu: [
      {
        nombre: "Costillas ahumadas de domingo",
        descripcion: "Media parrilla con papas gajo, ensaladita y salsa de la casa.",
        precio: 18500,
        foto: "/food-demo/m/carnes-2.jpg",
      },
      {
        nombre: "Costillar de cerdo con chimichurri",
        precio: 17500,
        foto: "/food-demo/m/carnes-6.jpg",
      },
      {
        nombre: "Parrillada campesina para uno",
        descripcion: "Pollo, res, cerdo y chorizo con papa asada, directo del asador de patio.",
        precio: 19500,
        foto: "/food-demo/m/carnes-7.jpg",
      },
      {
        nombre: "Lomo al carbón con verduritas",
        precio: 16500,
        foto: "/food-demo/m/carnes-3.jpg",
      },
      {
        nombre: "Puntas de res sobre tabla",
        precio: 15500,
        foto: "/food-demo/m/carnes-4.jpg",
      },
      {
        nombre: "Chorizos del llano con tortillas",
        precio: 11500,
        foto: "/food-demo/m/carnes-8.jpg",
      },
    ],
    rating: 4.5,
    resenas: 63,
    fotoPrincipal: "/food-demo/r/brasa-del-llano-1.jpg",
    galeria: ["/food-demo/r/brasa-del-llano-2.jpg", "/food-demo/r/brasa-del-llano-3.jpg"],
    horario: "Lun–Dom · 11:00 – 21:30",
    promociones: [
      { hora: "11:00", descuento: 20 },
      { hora: "12:30", descuento: 15 },
      { hora: "15:00", descuento: 30 },
      { hora: "16:00", descuento: 25 },
      { hora: "18:00", descuento: 20 },
      { hora: "19:30", descuento: 15 },
      { hora: "21:00", descuento: 10 },
    ],
  },
  {
    slug: "res-roble",
    nombre: "Res & Roble",
    descripcion:
      "Cortes selectos entre madera y acero, a un paso de la oficina. El plan perfecto para cerrar el día con una copa y un buen término.",
    categoria: "Carnes",
    cocina: "Grill urbano",
    zona: "Curridabat",
    direccion: "Plaza Granito, local 6",
    telefono: "+506 2555-0185",
    precioNivel: 4,
    precioPromedio: 25500,
    menu: [
      {
        nombre: "Ribeye al roble",
        descripcion: "Sellado sobre leña de roble y terminado con mantequilla de ajo negro.",
        precio: 29500,
        foto: "/food-demo/m/carnes-4.jpg",
      },
      {
        nombre: "Filete en reducción de hongos y vino tinto",
        precio: 27500,
        foto: "/food-demo/m/carnes-5.jpg",
      },
      {
        nombre: "New York con papas al romero",
        precio: 24500,
        foto: "/food-demo/m/carnes-3.jpg",
      },
      {
        nombre: "Costillitas glaseadas al bourbon",
        descripcion: "Glaseado dulce-ahumado tras cuatro horas de cocción lenta.",
        precio: 24500,
        foto: "/food-demo/m/carnes-6.jpg",
      },
      {
        nombre: "Brochetas urbanas de res y cerdo",
        precio: 21500,
        foto: "/food-demo/m/carnes-7.jpg",
      },
    ],
    rating: 4.7,
    resenas: 328,
    fotoPrincipal: "/food-demo/r/res-roble-1.jpg",
    galeria: ["/food-demo/r/res-roble-2.jpg", "/food-demo/r/res-roble-3.jpg"],
    horario: "Mar–Sáb · 12:00 – 22:30",
    promociones: [
      { hora: "12:00", descuento: 10 },
      { hora: "16:30", descuento: 20 },
      { hora: "18:00", descuento: 25 },
      { hora: "19:00", descuento: 35 },
      { hora: "20:00", descuento: 25 },
    ],
  },
];
