import type { RestauranteDemo } from "../tipos";

export const HAMBURGUESAS: RestauranteDemo[] = [
  {
    slug: "humo-y-oro",
    nombre: "Humo & Oro",
    descripcion:
      "Smash burgers selladas en plancha de acero, con pan brioche horneado cada mañana. Pasá al mediodía y probá la doble con queso madurado que ya es leyenda en el centro.",
    categoria: "Hamburguesas",
    cocina: "Smash burgers artesanales",
    zona: "San José centro",
    direccion: "Galería Alameda, local 5",
    telefono: "+506 2555-0121",
    precioNivel: 2,
    precioPromedio: 9500,
    menu: [
      {
        nombre: "Smash clásica de la casa",
        precio: 8400,
        foto: "/food-demo/m/hamburguesas-1.jpg",
      },
      {
        nombre: "Doble smash con queso madurado",
        descripcion:
          "La leyenda del centro: dos carnes selladas en plancha de acero y queso madurado fundido.",
        precio: 11900,
        foto: "/food-demo/m/hamburguesas-4.jpg",
      },
      {
        nombre: "Smash de tocineta ahumada",
        precio: 10600,
        foto: "/food-demo/m/hamburguesas-3.jpg",
      },
      {
        nombre: "Trío de mini smash",
        descripcion: "Tres minis en pan brioche del día, cada una con salsa distinta.",
        precio: 9700,
        foto: "/food-demo/m/hamburguesas-7.jpg",
      },
      {
        nombre: "Papas cargadas Humo & Oro",
        precio: 8300,
        foto: "/food-demo/m/hamburguesas-6.jpg",
      },
      {
        nombre: "Aros de cebolla dorados",
        precio: 5600,
        foto: "/food-demo/m/hamburguesas-8.jpg",
      },
    ],
    rating: 4.7,
    resenas: 312,
    fotoPrincipal: "/food-demo/r/humo-y-oro-1.jpg",
    galeria: ["/food-demo/r/humo-y-oro-2.jpg", "/food-demo/r/humo-y-oro-3.jpg"],
    horario: "Lun–Sáb · 11:30 – 22:00",
    promociones: [
      { hora: "11:30", descuento: 20 },
      { hora: "12:00", descuento: 30 },
      { hora: "12:30", descuento: 40 },
      { hora: "13:00", descuento: 30 },
      { hora: "13:30", descuento: 20 },
      { hora: "14:00", descuento: 10 },
    ],
  },
  {
    slug: "la-forja",
    nombre: "La Forja",
    descripcion:
      "Acá la carne pasa por brasa de leña antes de tocar el pan, y eso se siente en cada mordida. El plan perfecto para llegar con el grupo después de una vuelta por la Sabana.",
    categoria: "Hamburguesas",
    cocina: "Burgers a la leña",
    zona: "Sabana",
    direccion: "Plaza Brisa Oeste, local 14",
    telefono: "+506 2555-0134",
    precioNivel: 2,
    precioPromedio: 10500,
    menu: [
      {
        nombre: "Burger de la brasa con queso fundido",
        descripcion:
          "Doble carne que pasa por brasa de leña antes de tocar el pan; el humo se siente en cada mordida.",
        precio: 11800,
        foto: "/food-demo/m/hamburguesas-2.jpg",
      },
      {
        nombre: "Tocineta al carbón con cebolla dulce",
        precio: 12400,
        foto: "/food-demo/m/hamburguesas-3.jpg",
      },
      {
        nombre: "La Forja BBQ ahumada",
        descripcion: "Salsa BBQ de la casa reducida sobre el fuego de leña.",
        precio: 12900,
        foto: "/food-demo/m/hamburguesas-4.jpg",
      },
      {
        nombre: "Crispy de pollo a la leña",
        precio: 9800,
        foto: "/food-demo/m/hamburguesas-5.jpg",
      },
      {
        nombre: "Papas al fuego con queso y tocineta",
        precio: 8100,
        foto: "/food-demo/m/hamburguesas-6.jpg",
      },
      {
        nombre: "Aros de cebolla ahumados",
        precio: 5400,
        foto: "/food-demo/m/hamburguesas-8.jpg",
      },
    ],
    rating: 4.5,
    resenas: 183,
    fotoPrincipal: "/food-demo/r/la-forja-1.jpg",
    galeria: ["/food-demo/r/la-forja-2.jpg", "/food-demo/r/la-forja-3.jpg"],
    horario: "Mar–Dom · 12:00 – 22:30",
    promociones: [
      { hora: "16:30", descuento: 15 },
      { hora: "17:00", descuento: 25 },
      { hora: "17:30", descuento: 35 },
      { hora: "18:00", descuento: 30 },
      { hora: "19:00", descuento: 20 },
      { hora: "20:00", descuento: 10 },
    ],
  },
  {
    slug: "malanoche",
    nombre: "Malanoche",
    descripcion:
      "El plan nocturno de Heredia: burgers generosas, papas cargadas y cocina abierta hasta tarde. Si el hambre te agarra después de las nueve, este es tu lugar.",
    categoria: "Hamburguesas",
    cocina: "Burger bar nocturno",
    zona: "Heredia",
    direccion: "Centro Comercial Monte Claro, local 9",
    telefono: "+506 2555-0147",
    precioNivel: 2,
    precioPromedio: 11800,
    menu: [
      {
        nombre: "La Trasnochada doble",
        descripcion:
          "Doble carne, doble queso y tocineta para el hambre que llega después de las nueve.",
        precio: 13900,
        foto: "/food-demo/m/hamburguesas-4.jpg",
      },
      {
        nombre: "Burger de medianoche con tocineta",
        precio: 13200,
        foto: "/food-demo/m/hamburguesas-3.jpg",
      },
      {
        nombre: "La Última Ronda",
        precio: 11400,
        foto: "/food-demo/m/hamburguesas-1.jpg",
      },
      {
        nombre: "Crispy picante de medianoche",
        precio: 11600,
        foto: "/food-demo/m/hamburguesas-5.jpg",
      },
      {
        nombre: "Mini burgers del búho",
        precio: 12100,
        foto: "/food-demo/m/hamburguesas-7.jpg",
      },
      {
        nombre: "Papas cargadas Malanoche",
        descripcion: "La montaña de papas con queso fundido que pide la mesa entera.",
        precio: 9800,
        foto: "/food-demo/m/hamburguesas-6.jpg",
      },
      {
        nombre: "Aros de cebolla para compartir",
        precio: 7400,
        foto: "/food-demo/m/hamburguesas-8.jpg",
      },
    ],
    rating: 4.8,
    resenas: 476,
    fotoPrincipal: "/food-demo/r/malanoche-1.jpg",
    galeria: ["/food-demo/r/malanoche-2.jpg", "/food-demo/r/malanoche-3.jpg"],
    horario: "Mié–Lun · 17:00 – 23:30",
    promociones: [
      { hora: "19:00", descuento: 10 },
      { hora: "20:00", descuento: 25 },
      { hora: "20:30", descuento: 45 },
      { hora: "21:00", descuento: 50 },
      { hora: "21:30", descuento: 40 },
      { hora: "22:00", descuento: 30 },
      { hora: "22:30", descuento: 20 },
    ],
  },
  {
    slug: "porton-amarillo",
    nombre: "Portón Amarillo",
    descripcion:
      "Recetas de familia, torta molida en casa y vegetales de la zona en un local de barrio con mesas largas. Llegás por la burger y te quedás por el trato.",
    categoria: "Hamburguesas",
    cocina: "Burgers caseras de barrio",
    zona: "Cartago",
    direccion: "Plaza del Molino, local 6",
    telefono: "+506 2555-0158",
    precioNivel: 1,
    precioPromedio: 5800,
    menu: [
      {
        nombre: "Burger casada del Portón",
        descripcion:
          "Torta molida en casa con vegetales de la zona, como se ha hecho siempre en la familia.",
        precio: 6300,
        foto: "/food-demo/m/hamburguesas-1.jpg",
      },
      {
        nombre: "Doble del molino",
        precio: 7400,
        foto: "/food-demo/m/hamburguesas-2.jpg",
      },
      {
        nombre: "Pollo apanado de la abuela",
        descripcion: "Apanado crocante con el toque secreto de la receta familiar.",
        precio: 5900,
        foto: "/food-demo/m/hamburguesas-5.jpg",
      },
      {
        nombre: "Papitas con queso y pico de gallo",
        precio: 4800,
        foto: "/food-demo/m/hamburguesas-6.jpg",
      },
      {
        nombre: "Aros de cebolla caseros",
        precio: 3900,
        foto: "/food-demo/m/hamburguesas-8.jpg",
      },
    ],
    rating: 4.4,
    resenas: 67,
    fotoPrincipal: "/food-demo/r/porton-amarillo-1.jpg",
    galeria: [
      "/food-demo/r/porton-amarillo-2.jpg",
      "/food-demo/r/porton-amarillo-3.jpg",
    ],
    horario: "Lun–Dom · 11:00 – 21:00",
    promociones: [
      { hora: "11:00", descuento: 25 },
      { hora: "12:00", descuento: 15 },
      { hora: "17:00", descuento: 20 },
      { hora: "18:00", descuento: 30 },
      { hora: "19:00", descuento: 15 },
    ],
  },
  {
    slug: "andarivel",
    nombre: "Andarivel",
    descripcion:
      "Burgers de autor con salsas propias y cerveza artesanal de grifo, en un local recién estrenado en Santa Ana. Animate al trío de mini burgers para probar de todo.",
    categoria: "Hamburguesas",
    cocina: "Burgers de autor",
    zona: "Santa Ana",
    direccion: "Centro Gastronómico Valle Lindo, local 18",
    telefono: "+506 2555-0169",
    precioNivel: 2,
    precioPromedio: 12500,
    menu: [
      {
        nombre: "Trío de mini burgers de autor",
        descripcion:
          "La firma de la casa: tres minis distintas para probar de todo, cada una con su salsa propia.",
        precio: 13500,
        foto: "/food-demo/m/hamburguesas-7.jpg",
      },
      {
        nombre: "La Andarivel de queso azul",
        precio: 14200,
        foto: "/food-demo/m/hamburguesas-2.jpg",
      },
      {
        nombre: "Smash trufada doble",
        descripcion: "Doble carne con mayonesa de trufa y queso fundido al momento.",
        precio: 14800,
        foto: "/food-demo/m/hamburguesas-4.jpg",
      },
      {
        nombre: "Pollo crocante en salsa de la casa",
        precio: 11900,
        foto: "/food-demo/m/hamburguesas-5.jpg",
      },
      {
        nombre: "Clásica de la barra",
        precio: 11400,
        foto: "/food-demo/m/hamburguesas-1.jpg",
      },
      {
        nombre: "Papas bravas con queso fundido",
        precio: 9600,
        foto: "/food-demo/m/hamburguesas-6.jpg",
      },
      {
        nombre: "Aros en tempura de cerveza artesanal",
        precio: 7800,
        foto: "/food-demo/m/hamburguesas-8.jpg",
      },
    ],
    rating: 4.6,
    resenas: 141,
    fotoPrincipal: "/food-demo/r/andarivel-1.jpg",
    galeria: ["/food-demo/r/andarivel-2.jpg", "/food-demo/r/andarivel-3.jpg"],
    horario: "Mar–Dom · 12:00 – 23:00",
    promociones: [
      { hora: "14:30", descuento: 30 },
      { hora: "15:30", descuento: 45 },
      { hora: "16:30", descuento: 35 },
      { hora: "17:30", descuento: 25 },
      { hora: "18:30", descuento: 15 },
      { hora: "19:30", descuento: 10 },
      { hora: "21:00", descuento: 20 },
    ],
    esNuevo: true,
  },
];
