import type { RestauranteDemo } from "../tipos";

export const ITALIANA: RestauranteDemo[] = [
  {
    slug: "terracota-trattoria",
    nombre: "Terracota Trattoria",
    descripcion:
      "Pastas hechas en casa y salsas que arrancan a cocinarse desde la mañana. Vení por el pappardelle al ragú y quedate por el tiramisú de la casa.",
    categoria: "Italiana",
    cocina: "Trattoria toscana contemporánea",
    zona: "Escazú",
    direccion: "Plaza Vindel, local 14",
    telefono: "+506 2555-0114",
    precioNivel: 3,
    precioPromedio: 17500,
    menu: [
      {
        nombre: "Caprese de mozzarella fior di latte",
        descripcion: "Tomate cherry, albahaca fresca y aceite de oliva toscano.",
        precio: 12400,
        foto: "/food-demo/m/italiana-6.jpg",
      },
      {
        nombre: "Fettuccine a la carbonara con panceta",
        precio: 20800,
        foto: "/food-demo/m/italiana-1.jpg",
      },
      {
        nombre: "Lasaña boloñesa de la abuela",
        descripcion: "Capas de pasta fresca con ragú cocinado seis horas.",
        precio: 19600,
        foto: "/food-demo/m/italiana-2.jpg",
      },
      {
        nombre: "Risotto cremoso de hongos porcini",
        precio: 21900,
        foto: "/food-demo/m/italiana-4.jpg",
      },
      {
        nombre: "Tortellini de ricota en mantequilla de salvia",
        precio: 19400,
        foto: "/food-demo/m/italiana-3.jpg",
      },
      {
        nombre: "Tiramisú clásico de la casa",
        descripcion: "Bizcocho embebido en espresso y crema de mascarpone.",
        precio: 7400,
        foto: "/food-demo/m/italiana-5.jpg",
      },
    ],
    rating: 4.8,
    resenas: 287,
    fotoPrincipal: "/food-demo/r/terracota-trattoria-1.jpg",
    galeria: [
      "/food-demo/r/terracota-trattoria-2.jpg",
      "/food-demo/r/terracota-trattoria-3.jpg",
    ],
    horario: "Lun–Dom · 12:00 – 22:00",
    promociones: [
      { hora: "12:30", descuento: 15 },
      { hora: "17:00", descuento: 30 },
      { hora: "17:30", descuento: 40 },
      { hora: "18:00", descuento: 35 },
      { hora: "19:30", descuento: 20 },
      { hora: "21:00", descuento: 10 },
    ],
  },
  {
    slug: "piazzetta-nueve",
    nombre: "Piazzetta Nueve",
    descripcion:
      "En pleno centro capitalino, un rincón italiano con menú de almuerzo que cambia cada semana. Ideal si andás con poco tiempo y ganas de comer bien.",
    categoria: "Italiana",
    cocina: "Cocina italiana urbana",
    zona: "San José centro",
    direccion: "Avenida Segunda, edificio Casa Roble, local 3",
    telefono: "+506 2555-0127",
    precioNivel: 2,
    precioPromedio: 11200,
    menu: [
      {
        nombre: "Ñoquis al pomodoro con perlas de mozzarella",
        descripcion: "El favorito del almuerzo: tomate rustido y albahaca.",
        precio: 12400,
        foto: "/food-demo/m/italiana-7.jpg",
      },
      {
        nombre: "Linguine cremoso con tocineta ahumada",
        precio: 13600,
        foto: "/food-demo/m/italiana-1.jpg",
      },
      {
        nombre: "Lasaña casera del mediodía",
        precio: 13900,
        foto: "/food-demo/m/italiana-2.jpg",
      },
      {
        nombre: "Focaccia de romero con aceite de oliva",
        descripcion: "Horneada cada mañana, perfecta para compartir.",
        precio: 6900,
        foto: "/food-demo/m/italiana-8.jpg",
      },
      {
        nombre: "Tortellini al burro con parmesano",
        precio: 12800,
        foto: "/food-demo/m/italiana-3.jpg",
      },
      {
        nombre: "Caprese exprés del mercado",
        precio: 7400,
        foto: "/food-demo/m/italiana-6.jpg",
      },
    ],
    rating: 4.6,
    resenas: 164,
    fotoPrincipal: "/food-demo/r/piazzetta-nueve-1.jpg",
    galeria: [
      "/food-demo/r/piazzetta-nueve-2.jpg",
      "/food-demo/r/piazzetta-nueve-3.jpg",
    ],
    horario: "Lun–Sáb · 11:30 – 21:30",
    promociones: [
      { hora: "11:30", descuento: 45 },
      { hora: "12:00", descuento: 35 },
      { hora: "12:30", descuento: 25 },
      { hora: "13:30", descuento: 15 },
      { hora: "14:00", descuento: 10 },
      { hora: "18:30", descuento: 20 },
    ],
  },
  {
    slug: "fuoco-lento",
    nombre: "Fuoco Lento",
    descripcion:
      "Acá todo pasa por la brasa y el horno de leña: focaccias, verduras rostizadas y un ossobuco que se deshace solo. Perfecto para cenar sin prisa.",
    categoria: "Italiana",
    cocina: "Osteria al fuego de leña",
    zona: "Santa Ana",
    direccion: "Plaza Monteflor, local 6",
    telefono: "+506 2555-0138",
    precioNivel: 3,
    precioPromedio: 20500,
    menu: [
      {
        nombre: "Focaccia de masa madre al horno de leña",
        descripcion: "Masa madre de 48 horas con romero y sal de mar.",
        precio: 8400,
        foto: "/food-demo/m/italiana-8.jpg",
      },
      {
        nombre: "Caprese de búfala con tomates asados",
        precio: 14900,
        foto: "/food-demo/m/italiana-6.jpg",
      },
      {
        nombre: "Tagliolini a la crema con guanciale crocante",
        precio: 25400,
        foto: "/food-demo/m/italiana-1.jpg",
      },
      {
        nombre: "Lasaña de res braseada a la leña",
        descripcion: "Ragú braseado ocho horas sobre las brasas.",
        precio: 25900,
        foto: "/food-demo/m/italiana-2.jpg",
      },
      {
        nombre: "Risotto de hongos silvestres",
        descripcion: "Arborio cremoso con hongos dorados al carbón.",
        precio: 27400,
        foto: "/food-demo/m/italiana-4.jpg",
      },
      {
        nombre: "Ñoquis al pomodoro de tomate rostizado",
        precio: 24400,
        foto: "/food-demo/m/italiana-7.jpg",
      },
      {
        nombre: "Tiramisú al amaretto",
        precio: 9900,
        foto: "/food-demo/m/italiana-5.jpg",
      },
    ],
    rating: 4.9,
    resenas: 412,
    fotoPrincipal: "/food-demo/r/fuoco-lento-1.jpg",
    galeria: [
      "/food-demo/r/fuoco-lento-2.jpg",
      "/food-demo/r/fuoco-lento-3.jpg",
    ],
    horario: "Mié–Dom · 17:00 – 23:00",
    promociones: [
      { hora: "17:00", descuento: 20 },
      { hora: "18:00", descuento: 10 },
      { hora: "19:30", descuento: 15 },
      { hora: "20:00", descuento: 30 },
      { hora: "20:30", descuento: 50 },
      { hora: "21:00", descuento: 45 },
      { hora: "21:30", descuento: 35 },
    ],
  },
  {
    slug: "sfoglia-dorada",
    nombre: "La Sfoglia Dorada",
    descripcion:
      "Recién abiertos en San Pedro, con una barra donde ves estirar la pasta al momento. Los raviolis de la casa ya tienen fama en el barrio.",
    categoria: "Italiana",
    cocina: "Pastas frescas de autor",
    zona: "San Pedro",
    direccion: "Centro Comercial Valle Lirio, local 12",
    telefono: "+506 2555-0142",
    precioNivel: 2,
    precioPromedio: 9500,
    menu: [
      {
        nombre: "Tortellini de queso en mantequilla dorada",
        descripcion: "Hechos frente a vos en la barra de pasta fresca.",
        precio: 11400,
        foto: "/food-demo/m/italiana-3.jpg",
      },
      {
        nombre: "Espaguetis a la crema con pancetta",
        precio: 11900,
        foto: "/food-demo/m/italiana-1.jpg",
      },
      {
        nombre: "Ñoquis de papa al pomodoro",
        precio: 10400,
        foto: "/food-demo/m/italiana-7.jpg",
      },
      {
        nombre: "Focaccia tibia recién horneada",
        precio: 5400,
        foto: "/food-demo/m/italiana-8.jpg",
      },
      {
        nombre: "Tiramisú del día",
        descripcion: "En porción individual, con cacao espolvoreado al momento.",
        precio: 5200,
        foto: "/food-demo/m/italiana-5.jpg",
      },
    ],
    rating: 4.4,
    resenas: 41,
    fotoPrincipal: "/food-demo/r/sfoglia-dorada-1.jpg",
    galeria: [
      "/food-demo/r/sfoglia-dorada-2.jpg",
      "/food-demo/r/sfoglia-dorada-3.jpg",
    ],
    horario: "Mar–Dom · 11:30 – 21:00",
    promociones: [
      { hora: "12:00", descuento: 25 },
      { hora: "14:30", descuento: 35 },
      { hora: "15:00", descuento: 30 },
      { hora: "19:00", descuento: 15 },
    ],
    esNuevo: true,
  },
  {
    slug: "campanella-cucina",
    nombre: "Campanella Cucina",
    descripcion:
      "Sabores del sur de Italia con producto local: berenjenas al horno, tomate confitado y burrata fresca. Un plan tranquilo para llegar en familia.",
    categoria: "Italiana",
    cocina: "Cocina del sur de Italia",
    zona: "Heredia",
    direccion: "Paseo Los Robles, local 9",
    telefono: "+506 2555-0159",
    precioNivel: 2,
    precioPromedio: 12800,
    menu: [
      {
        nombre: "Caprese pugliese con tomate confitado",
        descripcion: "Mozzarella fresca, tomate confitado y orégano de la huerta.",
        precio: 10900,
        foto: "/food-demo/m/italiana-6.jpg",
      },
      {
        nombre: "Lasaña napolitana de berenjena",
        descripcion: "Berenjena al horno, pomodoro y queso fundido.",
        precio: 14400,
        foto: "/food-demo/m/italiana-2.jpg",
      },
      {
        nombre: "Risotto campesino de hongos",
        precio: 14900,
        foto: "/food-demo/m/italiana-4.jpg",
      },
      {
        nombre: "Ñoquis a la sorrentina",
        precio: 13400,
        foto: "/food-demo/m/italiana-7.jpg",
      },
      {
        nombre: "Tortelli de ricota y limón",
        precio: 13900,
        foto: "/food-demo/m/italiana-3.jpg",
      },
      {
        nombre: "Pan focaccia con tomate confitado",
        precio: 5900,
        foto: "/food-demo/m/italiana-8.jpg",
      },
    ],
    rating: 4.7,
    resenas: 233,
    fotoPrincipal: "/food-demo/r/campanella-cucina-1.jpg",
    galeria: [
      "/food-demo/r/campanella-cucina-2.jpg",
      "/food-demo/r/campanella-cucina-3.jpg",
    ],
    horario: "Lun–Dom · 12:00 – 21:00",
    promociones: [
      { hora: "12:00", descuento: 20 },
      { hora: "12:30", descuento: 15 },
      { hora: "13:00", descuento: 10 },
      { hora: "18:00", descuento: 25 },
      { hora: "19:00", descuento: 20 },
      { hora: "20:00", descuento: 15 },
    ],
  },
];
