import type { RestauranteDemo } from "../tipos";

export const MEDITERRANEA: RestauranteDemo[] = [
  {
    slug: "puerto-egeo",
    nombre: "Puerto Egeo",
    descripcion:
      "Mezze frescos, pulpo a la brasa y vinos blancos en una terraza que se siente de vacaciones. Vení al mediodía, que es cuando la cocina saca su mejor versión.",
    categoria: "Mediterránea",
    cocina: "Mezze y mariscos del Egeo",
    zona: "Escazú",
    direccion: "Plaza Miravalle, local 14",
    telefono: "+506 2555-0142",
    precioNivel: 3,
    precioPromedio: 18500,
    menu: [
      {
        nombre: "Pulpo a la brasa con limón asado",
        descripcion: "Cocción lenta y carbón, servido con papas al romero.",
        precio: 19900,
        foto: "/food-demo/m/mediterranea-2.jpg",
      },
      {
        nombre: "Hummus con garbanzos tostados y pita caliente",
        precio: 9900,
        foto: "/food-demo/m/mediterranea-1.jpg",
      },
      {
        nombre: "Ensalada griega con feta de barril",
        precio: 11900,
        foto: "/food-demo/m/mediterranea-3.jpg",
      },
      {
        nombre: "Arroz marinero del Egeo",
        descripcion: "Arroz cremoso con camarones, mejillones y almejas.",
        precio: 24500,
        foto: "/food-demo/m/mediterranea-5.jpg",
      },
      {
        nombre: "Cordero al carbón con hierbas del monte",
        precio: 24900,
        foto: "/food-demo/m/mediterranea-8.jpg",
      },
      {
        nombre: "Baklava de pistacho con miel de azahar",
        precio: 7900,
        foto: "/food-demo/m/mediterranea-7.jpg",
      },
    ],
    rating: 4.8,
    resenas: 327,
    fotoPrincipal: "/food-demo/r/puerto-egeo-1.jpg",
    galeria: ["/food-demo/r/puerto-egeo-2.jpg", "/food-demo/r/puerto-egeo-3.jpg"],
    horario: "Lun–Dom · 11:30 – 22:00",
    promociones: [
      { hora: "11:30", descuento: 25 },
      { hora: "12:00", descuento: 40 },
      { hora: "12:30", descuento: 35 },
      { hora: "13:00", descuento: 25 },
      { hora: "13:30", descuento: 15 },
      { hora: "19:00", descuento: 10 },
    ],
  },
  {
    slug: "higo-y-brasa",
    nombre: "Higo & Brasa",
    descripcion:
      "Cocina levantina al fuego: hummus sedoso, cordero de cocción lenta y pan recién salido del horno. Perfecto si te gusta cenar temprano y sin prisas.",
    categoria: "Mediterránea",
    cocina: "Levantina a la brasa",
    zona: "Santa Ana",
    direccion: "Centro Comercial Río Claro, local 6",
    telefono: "+506 2555-0187",
    precioNivel: 3,
    precioPromedio: 21000,
    menu: [
      {
        nombre: "Cordero de doce horas a la brasa",
        descripcion: "Cocción lenta hasta deshacerse, con especias levantinas.",
        precio: 29900,
        foto: "/food-demo/m/mediterranea-8.jpg",
      },
      {
        nombre: "Pulpo a las brasas con tahini de limón",
        precio: 24900,
        foto: "/food-demo/m/mediterranea-2.jpg",
      },
      {
        nombre: "Pincho de pollo za'atar con papas",
        precio: 18900,
        foto: "/food-demo/m/mediterranea-4.jpg",
      },
      {
        nombre: "Hummus sedoso con cordero y piñones",
        descripcion: "Nuestro clásico: tibio, con pan recién salido del horno.",
        precio: 14900,
        foto: "/food-demo/m/mediterranea-1.jpg",
      },
      {
        nombre: "Falafel de la casa con encurtidos",
        precio: 12900,
        foto: "/food-demo/m/mediterranea-6.jpg",
      },
      {
        nombre: "Baklava tibio de pistacho",
        precio: 8900,
        foto: "/food-demo/m/mediterranea-7.jpg",
      },
    ],
    rating: 4.9,
    resenas: 76,
    fotoPrincipal: "/food-demo/r/higo-y-brasa-1.jpg",
    galeria: ["/food-demo/r/higo-y-brasa-2.jpg", "/food-demo/r/higo-y-brasa-3.jpg"],
    horario: "Mar–Dom · 12:00 – 22:30",
    promociones: [
      { hora: "16:30", descuento: 20 },
      { hora: "17:00", descuento: 35 },
      { hora: "17:30", descuento: 45 },
      { hora: "18:00", descuento: 30 },
      { hora: "18:30", descuento: 20 },
      { hora: "19:30", descuento: 10 },
    ],
  },
  {
    slug: "mar-de-olivos",
    nombre: "Mar de Olivos",
    descripcion:
      "Una taberna griega de barrio con ensaladas generosas, souvlaki al carbón y postres de miel. El plan ideal para hacer larga la tarde por Sabana.",
    categoria: "Mediterránea",
    cocina: "Taberna griega",
    zona: "Sabana",
    direccion: "Boulevard Las Palmas, local 3",
    telefono: "+506 2555-0163",
    precioNivel: 3,
    precioPromedio: 15500,
    menu: [
      {
        nombre: "Souvlaki de cerdo al carbón",
        descripcion: "El plato de la casa: pincho jugoso con papas y limón.",
        precio: 13900,
        foto: "/food-demo/m/mediterranea-4.jpg",
      },
      {
        nombre: "Ensalada griega de la huerta",
        precio: 10900,
        foto: "/food-demo/m/mediterranea-3.jpg",
      },
      {
        nombre: "Hummus de la taberna con pita",
        precio: 8900,
        foto: "/food-demo/m/mediterranea-1.jpg",
      },
      {
        nombre: "Pulpo de roca a la parrilla",
        descripcion: "Tierno por dentro, tostado por fuera, con aceite de oliva.",
        precio: 19900,
        foto: "/food-demo/m/mediterranea-2.jpg",
      },
      {
        nombre: "Cordero al horno con papas de limón",
        precio: 22900,
        foto: "/food-demo/m/mediterranea-8.jpg",
      },
      {
        nombre: "Baklava con miel y nuez",
        precio: 6900,
        foto: "/food-demo/m/mediterranea-7.jpg",
      },
    ],
    rating: 4.5,
    resenas: 452,
    fotoPrincipal: "/food-demo/r/mar-de-olivos-1.jpg",
    galeria: ["/food-demo/r/mar-de-olivos-2.jpg", "/food-demo/r/mar-de-olivos-3.jpg"],
    horario: "Lun–Sáb · 11:00 – 21:00",
    promociones: [
      { hora: "12:00", descuento: 15 },
      { hora: "13:00", descuento: 20 },
      { hora: "14:30", descuento: 35 },
      { hora: "15:00", descuento: 50 },
      { hora: "16:00", descuento: 40 },
      { hora: "17:00", descuento: 25 },
      { hora: "18:30", descuento: 10 },
    ],
  },
  {
    slug: "casa-terral",
    nombre: "Casa Terral",
    descripcion:
      "Del sur de Francia a la costa ibérica: arroces melosos, ratatouille y tapas para compartir a la luz de las velas. Reservá tarde y agarrá el ambiente en su punto.",
    categoria: "Mediterránea",
    cocina: "Provenzal e ibérica",
    zona: "Belén",
    direccion: "Plaza del Roble, local 21",
    telefono: "+506 2555-0129",
    precioNivel: 3,
    precioPromedio: 17000,
    menu: [
      {
        nombre: "Arroz meloso de mariscos",
        descripcion: "Camarones, mejillones y almejas sobre arroz al azafrán.",
        precio: 21900,
        foto: "/food-demo/m/mediterranea-5.jpg",
      },
      {
        nombre: "Chuletitas de cordero a la provenzal",
        descripcion: "Con hierbas de la Provenza y verduritas salteadas.",
        precio: 23900,
        foto: "/food-demo/m/mediterranea-8.jpg",
      },
      {
        nombre: "Pulpo a la brasa con pimentón",
        precio: 19900,
        foto: "/food-demo/m/mediterranea-2.jpg",
      },
      {
        nombre: "Crema de garbanzo al aceite de oliva",
        precio: 8900,
        foto: "/food-demo/m/mediterranea-1.jpg",
      },
      {
        nombre: "Ensalada de tomate, queso y aceitunas",
        precio: 9400,
        foto: "/food-demo/m/mediterranea-3.jpg",
      },
      {
        nombre: "Brocheta ibérica a las brasas",
        precio: 15900,
        foto: "/food-demo/m/mediterranea-4.jpg",
      },
    ],
    rating: 4.7,
    resenas: 189,
    fotoPrincipal: "/food-demo/r/casa-terral-1.jpg",
    galeria: ["/food-demo/r/casa-terral-2.jpg", "/food-demo/r/casa-terral-3.jpg"],
    horario: "Mié–Dom · 17:00 – 23:00",
    promociones: [
      { hora: "17:30", descuento: 10 },
      { hora: "18:30", descuento: 15 },
      { hora: "19:30", descuento: 20 },
      { hora: "20:00", descuento: 30 },
      { hora: "20:30", descuento: 35 },
      { hora: "21:00", descuento: 25 },
      { hora: "21:30", descuento: 15 },
    ],
  },
];
