import type { RestauranteDemo } from "../tipos";

export const SUSHI: RestauranteDemo[] = [
  {
    slug: "marea-nikkei",
    nombre: "Marea Nikkei",
    descripcion:
      "Barra nikkei donde la técnica japonesa se encuentra con el fuego peruano. Probá el tartar de atún de la casa y vas a entender por qué la gente vuelve.",
    categoria: "Sushi",
    cocina: "Fusión nikkei",
    zona: "Escazú",
    direccion: "Plaza Altavista, local 22",
    telefono: "+506 2555-0121",
    precioNivel: 3,
    precioPromedio: 18500,
    menu: [
      {
        nombre: "Tartar de atún al ají amarillo",
        descripcion: "Atún fresco con leche de tigre y crocante de camote.",
        precio: 16800,
        foto: "/food-demo/m/sushi-4.jpg",
      },
      {
        nombre: "Nigiri de salmón flameado",
        precio: 14500,
        foto: "/food-demo/m/sushi-2.jpg",
      },
      {
        nombre: "Tabla nikkei del chef",
        descripcion: "Doce piezas que mezclan barra fría y toques al fuego.",
        precio: 22800,
        foto: "/food-demo/m/sushi-1.jpg",
      },
      {
        nombre: "Sashimi de salmón en leche de tigre",
        precio: 19500,
        foto: "/food-demo/m/sushi-7.jpg",
      },
      {
        nombre: "Camarones crocantes al panko",
        precio: 18900,
        foto: "/food-demo/m/sushi-6.jpg",
      },
      {
        nombre: "Yakisoba de mariscos al wok",
        precio: 21500,
        foto: "/food-demo/m/sushi-3.jpg",
      },
    ],
    rating: 4.8,
    resenas: 341,
    fotoPrincipal: "/food-demo/r/marea-nikkei-1.jpg",
    galeria: ["/food-demo/r/marea-nikkei-2.jpg", "/food-demo/r/marea-nikkei-3.jpg"],
    horario: "Mar–Dom · 12:00 – 22:30",
    promociones: [
      { hora: "12:30", descuento: 15 },
      { hora: "13:30", descuento: 10 },
      { hora: "17:00", descuento: 30 },
      { hora: "17:30", descuento: 40 },
      { hora: "18:00", descuento: 35 },
      { hora: "21:30", descuento: 20 },
    ],
  },
  {
    slug: "bruma-izakaya",
    nombre: "Bruma Izakaya",
    descripcion:
      "Luz baja, sake frío y platillos para compartir hasta tarde, al estilo de las izakayas de barrio. Ideal si andás buscando un plan de noche sin etiqueta.",
    categoria: "Sushi",
    cocina: "Izakaya japonesa",
    zona: "Rohrmoser",
    direccion: "Centro Comercial Faro Oeste, local 6",
    telefono: "+506 2555-0134",
    precioNivel: 2,
    precioPromedio: 11500,
    menu: [
      {
        nombre: "Yakitori de pollo y cebollín",
        precio: 8900,
        foto: "/food-demo/m/sushi-8.jpg",
      },
      {
        nombre: "Gyozas doradas a la plancha",
        descripcion: "Rellenas de cerdo y jengibre, con soya cítrica.",
        precio: 9500,
        foto: "/food-demo/m/sushi-5.jpg",
      },
      {
        nombre: "Ebi tempura con salsa tentsuyu",
        precio: 12500,
        foto: "/food-demo/m/sushi-6.jpg",
      },
      {
        nombre: "Yakisoba de la casa",
        precio: 11900,
        foto: "/food-demo/m/sushi-3.jpg",
      },
      {
        nombre: "Nigiri de salmón curado en sake",
        precio: 12800,
        foto: "/food-demo/m/sushi-2.jpg",
      },
      {
        nombre: "Sashimi de salmón con ponzu",
        precio: 13900,
        foto: "/food-demo/m/sushi-7.jpg",
      },
      {
        nombre: "Tabla del izakaya para compartir",
        descripcion: "Selección de la barra pensada para ir picando con sake.",
        precio: 15800,
        foto: "/food-demo/m/sushi-1.jpg",
      },
    ],
    rating: 4.6,
    resenas: 96,
    fotoPrincipal: "/food-demo/r/bruma-izakaya-1.jpg",
    galeria: ["/food-demo/r/bruma-izakaya-2.jpg", "/food-demo/r/bruma-izakaya-3.jpg"],
    horario: "Lun–Sáb · 17:00 – 23:00",
    promociones: [
      { hora: "17:00", descuento: 20 },
      { hora: "18:30", descuento: 10 },
      { hora: "20:00", descuento: 25 },
      { hora: "20:30", descuento: 35 },
      { hora: "21:00", descuento: 45 },
      { hora: "21:30", descuento: 40 },
    ],
  },
  {
    slug: "tinta-y-arroz",
    nombre: "Tinta y Arroz",
    descripcion:
      "Omakase de temporada con apenas doce campos en barra: el chef decide el menú y vos solo llegás con hambre.",
    categoria: "Sushi",
    cocina: "Barra de omakase",
    zona: "Lindora",
    direccion: "Boulevard Encino, local 3",
    telefono: "+506 2555-0147",
    precioNivel: 3,
    precioPromedio: 21000,
    menu: [
      {
        nombre: "Omakase corto de la barra",
        descripcion: "Cinco tiempos que cambian con la pesca del día.",
        precio: 26500,
        foto: "/food-demo/m/sushi-1.jpg",
      },
      {
        nombre: "Nigiri de salmón sellado con soplete",
        precio: 17500,
        foto: "/food-demo/m/sushi-2.jpg",
      },
      {
        nombre: "Sashimi de salmón de corte grueso",
        precio: 21500,
        foto: "/food-demo/m/sushi-7.jpg",
      },
      {
        nombre: "Tartar de atún con yema curada",
        descripcion: "Servido en cucharas, para comer de un bocado.",
        precio: 19800,
        foto: "/food-demo/m/sushi-4.jpg",
      },
      {
        nombre: "Tempura de camarón jumbo",
        precio: 18700,
        foto: "/food-demo/m/sushi-6.jpg",
      },
    ],
    rating: 4.9,
    resenas: 187,
    fotoPrincipal: "/food-demo/r/tinta-y-arroz-1.jpg",
    galeria: ["/food-demo/r/tinta-y-arroz-2.jpg", "/food-demo/r/tinta-y-arroz-3.jpg"],
    horario: "Mié–Dom · 18:00 – 23:30",
    promociones: [
      { hora: "18:00", descuento: 30 },
      { hora: "18:30", descuento: 20 },
      { hora: "19:30", descuento: 10 },
      { hora: "21:30", descuento: 25 },
      { hora: "22:30", descuento: 35 },
    ],
  },
  {
    slug: "nami-blanca",
    nombre: "Nami Blanca",
    descripcion:
      "Rolls frescos y temakis armados al momento, a unos pasos del ambiente universitario de San Pedro. Los combos rinden de verdad, llegá acompañado.",
    categoria: "Sushi",
    cocina: "Rolls y temaki",
    zona: "San Pedro",
    direccion: "Plaza Vitral, local 11",
    telefono: "+506 2555-0158",
    precioNivel: 2,
    precioPromedio: 9500,
    menu: [
      {
        nombre: "Combo de ocho rolls surtidos",
        descripcion: "Cuatro variedades de la casa, ideal para compartir.",
        precio: 12400,
        foto: "/food-demo/m/sushi-1.jpg",
      },
      {
        nombre: "Gyozas fritas de cerdo",
        precio: 7400,
        foto: "/food-demo/m/sushi-5.jpg",
      },
      {
        nombre: "Yakisoba de pollo al wok",
        precio: 8900,
        foto: "/food-demo/m/sushi-3.jpg",
      },
      {
        nombre: "Nigiri doble de salmón",
        precio: 8600,
        foto: "/food-demo/m/sushi-2.jpg",
      },
      {
        nombre: "Camarones tempura con salsa de anguila",
        descripcion: "Crocantes por fuera, con el dulzor de la unagi encima.",
        precio: 9800,
        foto: "/food-demo/m/sushi-6.jpg",
      },
      {
        nombre: "Brochetas yakitori glaseadas",
        precio: 8200,
        foto: "/food-demo/m/sushi-8.jpg",
      },
    ],
    rating: 4.5,
    resenas: 452,
    fotoPrincipal: "/food-demo/r/nami-blanca-1.jpg",
    galeria: ["/food-demo/r/nami-blanca-2.jpg", "/food-demo/r/nami-blanca-3.jpg"],
    horario: "Lun–Dom · 11:30 – 21:30",
    promociones: [
      { hora: "11:30", descuento: 40 },
      { hora: "12:00", descuento: 50 },
      { hora: "13:00", descuento: 30 },
      { hora: "13:30", descuento: 20 },
      { hora: "14:00", descuento: 15 },
      { hora: "16:30", descuento: 25 },
      { hora: "19:00", descuento: 10 },
    ],
  },
  {
    slug: "kuro-bambu",
    nombre: "Kuro Bambú",
    descripcion:
      "Sushi contemporáneo en un local íntimo de madera oscura y detalles de bambú. Las tardes entre semana traen los mejores descuentos, aprovechalas.",
    categoria: "Sushi",
    cocina: "Sushi contemporáneo",
    zona: "Curridabat",
    direccion: "Centro Comercial Río Cedro, local 9",
    telefono: "+506 2555-0169",
    precioNivel: 2,
    precioPromedio: 13000,
    menu: [
      {
        nombre: "Tabla bambú de doce piezas",
        descripcion: "La selección insignia de la casa, servida sobre madera oscura.",
        precio: 16800,
        foto: "/food-demo/m/sushi-1.jpg",
      },
      {
        nombre: "Sashimi de salmón con ajonjolí tostado",
        precio: 14700,
        foto: "/food-demo/m/sushi-7.jpg",
      },
      {
        nombre: "Gyozas de la casa al vapor",
        precio: 9900,
        foto: "/food-demo/m/sushi-5.jpg",
      },
      {
        nombre: "Yakitori de pollo con negi",
        precio: 10800,
        foto: "/food-demo/m/sushi-8.jpg",
      },
      {
        nombre: "Tartar de atún en cuchara",
        descripcion: "Bocados fríos con toque de wasabi y ajonjolí.",
        precio: 13600,
        foto: "/food-demo/m/sushi-4.jpg",
      },
      {
        nombre: "Nigiri de salmón ahumado en frío",
        precio: 12300,
        foto: "/food-demo/m/sushi-2.jpg",
      },
      {
        nombre: "Ebi crocante en panko",
        precio: 12900,
        foto: "/food-demo/m/sushi-6.jpg",
      },
    ],
    rating: 4.7,
    resenas: 63,
    fotoPrincipal: "/food-demo/r/kuro-bambu-1.jpg",
    galeria: ["/food-demo/r/kuro-bambu-2.jpg", "/food-demo/r/kuro-bambu-3.jpg"],
    horario: "Lun–Dom · 12:00 – 21:00",
    promociones: [
      { hora: "12:00", descuento: 10 },
      { hora: "14:00", descuento: 20 },
      { hora: "15:30", descuento: 30 },
      { hora: "16:30", descuento: 25 },
      { hora: "18:00", descuento: 15 },
      { hora: "20:00", descuento: 20 },
    ],
  },
];
