export type Reserva = {
  id: string;
  fecha: string;
  nombre: string | null;
  contacto: string | null;
  tipo_evento: string | null;
  invitados: number | null;
  estado: "pendiente" | "confirmada" | "rechazada" | "bloqueada";
  horario_bloque: "manana_tarde" | "tarde_noche" | null;
  monto_total: number | null;
  metodo_pago: "sinpe" | "transferencia" | null;
  deposito_monto: number | null;
  deposito_comprobante_url: string | null;
  deposito_validado: boolean;
  evento_pagado: boolean;
  terminos_aceptados: boolean;
  notas: string | null;
  origen: "web" | "manual";
  created_at: string;
};
